eureka:
  instance:
    #hostname: "${HOSTNAME}.eureka"
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      #defaultZone: ${EUREKA_SERVER_ADDRESS}
      defaultZone: http://localhost:8761/eureka
