eureka:
  instance:
    preferIpAddress: true
    #hostname: eureka-0
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      #defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
